// Automatically generated by the Fast Binary Encoding compiler, do not modify!
// https://github.com/chronoxor/FastBinaryEncoding
// Source: FixHub.fbe
// Version: 1.7.0.0

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Runtime.Serialization;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace proto {

    public struct OrderStatus : IComparable, IComparable<OrderStatus>, IEquatable<OrderStatus>
    {
        public byte Value { get; internal set; }

        public OrderStatus(byte value) : this()
        {
            Value = value;
        }

        public OrderStatus(OrderStatus value) : this()
        {
            Value = value.Value;
        }

        public int CompareTo(object other)
        {
            return Value.CompareTo(((OrderStatus)other).Value);
        }

        public int CompareTo(OrderStatus other)
        {
            return Value.CompareTo(other.Value);
        }

        public override bool Equals(object other)
        {
            return (other is OrderStatus value) && Value.Equals(value.Value);
        }

        public bool Equals(OrderStatus other)
        {
            return Value.Equals(other.Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }

        public static bool operator==(OrderStatus value1, OrderStatus value2)
        {
            return value1.Value == value2.Value;
        }

        public static bool operator!=(OrderStatus value1, OrderStatus value2)
        {
            return value1.Value != value2.Value;
        }

        public static OrderStatus Default => new OrderStatus();

        public static FBE.FieldModelValueType<OrderStatus> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelOrderStatus(buffer, offset); }

        public const byte _NEW_ = (byte)0 + 0;
        public const byte _PARTIALLY_FILLED_ = (byte)1 + 0;
        public const byte _FILLED_ = (byte)2 + 0;
        public const byte _DONE_FOR_DAY_ = (byte)3 + 0;
        public const byte _CANCELED_ = (byte)4 + 0;
        public const byte _PENDING_CANCEL_ = (byte)6 + 0;
        public const byte _STOPPED_ = (byte)7 + 0;
        public const byte _REJECTED_ = (byte)8 + 0;
        public const byte _SUSPENDED_ = (byte)9 + 0;
        public const byte _PENDING_NEW_ = (byte)9 + 1;
        public const byte _CALCULATED_ = (byte)9 + 2;
        public const byte _EXPIRED_ = (byte)9 + 3;
        public const byte _ACCEPTED_FOR_BIDDING_ = (byte)9 + 4;
        public const byte _PENDING_REPLACE_ = (byte)9 + 5;

        public static OrderStatus NEW = new OrderStatus(_NEW_);
        public static OrderStatus PARTIALLY_FILLED = new OrderStatus(_PARTIALLY_FILLED_);
        public static OrderStatus FILLED = new OrderStatus(_FILLED_);
        public static OrderStatus DONE_FOR_DAY = new OrderStatus(_DONE_FOR_DAY_);
        public static OrderStatus CANCELED = new OrderStatus(_CANCELED_);
        public static OrderStatus PENDING_CANCEL = new OrderStatus(_PENDING_CANCEL_);
        public static OrderStatus STOPPED = new OrderStatus(_STOPPED_);
        public static OrderStatus REJECTED = new OrderStatus(_REJECTED_);
        public static OrderStatus SUSPENDED = new OrderStatus(_SUSPENDED_);
        public static OrderStatus PENDING_NEW = new OrderStatus(_PENDING_NEW_);
        public static OrderStatus CALCULATED = new OrderStatus(_CALCULATED_);
        public static OrderStatus EXPIRED = new OrderStatus(_EXPIRED_);
        public static OrderStatus ACCEPTED_FOR_BIDDING = new OrderStatus(_ACCEPTED_FOR_BIDDING_);
        public static OrderStatus PENDING_REPLACE = new OrderStatus(_PENDING_REPLACE_);

        public override string ToString()
        {
            if (this == NEW) return "NEW";
            if (this == PARTIALLY_FILLED) return "PARTIALLY_FILLED";
            if (this == FILLED) return "FILLED";
            if (this == DONE_FOR_DAY) return "DONE_FOR_DAY";
            if (this == CANCELED) return "CANCELED";
            if (this == PENDING_CANCEL) return "PENDING_CANCEL";
            if (this == STOPPED) return "STOPPED";
            if (this == REJECTED) return "REJECTED";
            if (this == SUSPENDED) return "SUSPENDED";
            if (this == PENDING_NEW) return "PENDING_NEW";
            if (this == CALCULATED) return "CALCULATED";
            if (this == EXPIRED) return "EXPIRED";
            if (this == ACCEPTED_FOR_BIDDING) return "ACCEPTED_FOR_BIDDING";
            if (this == PENDING_REPLACE) return "PENDING_REPLACE";
            return "<unknown>";
        }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding OrderStatus field model
    public class FieldModelOrderStatus : FieldModelValueType<OrderStatus>
    {
        public FieldModelOrderStatus(Buffer buffer, long offset) : base(buffer, offset) {}

        // Get the field size
        public override long FBESize => 1;

        // Clone the field model
        public override FieldModelValueType<OrderStatus> Clone() { return new FieldModelOrderStatus(_buffer, _offset); }

        // Get the value
        public override void Get(out OrderStatus value) { Get(out value, OrderStatus.Default); }
        public override void Get(out OrderStatus value, OrderStatus defaults)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
            {
                value = defaults;
                return;
            }

            value = new OrderStatus((byte)ReadUInt8(FBEOffset));
        }

        // Set the value
        public override void Set(OrderStatus value)
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return;

            Write(FBEOffset, value.Value);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct Action : IComparable, IComparable<Action>, IEquatable<Action>
    {
        public byte Value { get; internal set; }

        public Action(byte value) : this()
        {
            Value = value;
        }

        public Action(Action value) : this()
        {
            Value = value.Value;
        }

        public int CompareTo(object other)
        {
            return Value.CompareTo(((Action)other).Value);
        }

        public int CompareTo(Action other)
        {
            return Value.CompareTo(other.Value);
        }

        public override bool Equals(object other)
        {
            return (other is Action value) && Value.Equals(value.Value);
        }

        public bool Equals(Action other)
        {
            return Value.Equals(other.Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }

        public static bool operator==(Action value1, Action value2)
        {
            return value1.Value == value2.Value;
        }

        public static bool operator!=(Action value1, Action value2)
        {
            return value1.Value != value2.Value;
        }

        public static Action Default => new Action();

        public static FBE.FieldModelValueType<Action> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelAction(buffer, offset); }

        public const byte _CONNECT_ = (byte)1 + 0;
        public const byte _DISCONNECT_ = (byte)2 + 0;
        public const byte _SET_SEQUENCE_ = (byte)3 + 0;
        public const byte _RESET_SEQUENCE_ = (byte)4 + 0;

        public static Action CONNECT = new Action(_CONNECT_);
        public static Action DISCONNECT = new Action(_DISCONNECT_);
        public static Action SET_SEQUENCE = new Action(_SET_SEQUENCE_);
        public static Action RESET_SEQUENCE = new Action(_RESET_SEQUENCE_);

        public override string ToString()
        {
            if (this == CONNECT) return "CONNECT";
            if (this == DISCONNECT) return "DISCONNECT";
            if (this == SET_SEQUENCE) return "SET_SEQUENCE";
            if (this == RESET_SEQUENCE) return "RESET_SEQUENCE";
            return "<unknown>";
        }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Action field model
    public class FieldModelAction : FieldModelValueType<Action>
    {
        public FieldModelAction(Buffer buffer, long offset) : base(buffer, offset) {}

        // Get the field size
        public override long FBESize => 1;

        // Clone the field model
        public override FieldModelValueType<Action> Clone() { return new FieldModelAction(_buffer, _offset); }

        // Get the value
        public override void Get(out Action value) { Get(out value, Action.Default); }
        public override void Get(out Action value, Action defaults)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
            {
                value = defaults;
                return;
            }

            value = new Action((byte)ReadUInt8(FBEOffset));
        }

        // Set the value
        public override void Set(Action value)
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return;

            Write(FBEOffset, value.Value);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct MessageStatus : IComparable, IComparable<MessageStatus>, IEquatable<MessageStatus>
    {
        public byte Value { get; internal set; }

        public MessageStatus(byte value) : this()
        {
            Value = value;
        }

        public MessageStatus(MessageStatus value) : this()
        {
            Value = value.Value;
        }

        public int CompareTo(object other)
        {
            return Value.CompareTo(((MessageStatus)other).Value);
        }

        public int CompareTo(MessageStatus other)
        {
            return Value.CompareTo(other.Value);
        }

        public override bool Equals(object other)
        {
            return (other is MessageStatus value) && Value.Equals(value.Value);
        }

        public bool Equals(MessageStatus other)
        {
            return Value.Equals(other.Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }

        public static bool operator==(MessageStatus value1, MessageStatus value2)
        {
            return value1.Value == value2.Value;
        }

        public static bool operator!=(MessageStatus value1, MessageStatus value2)
        {
            return value1.Value != value2.Value;
        }

        public static MessageStatus Default => new MessageStatus();

        public static FBE.FieldModelValueType<MessageStatus> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelMessageStatus(buffer, offset); }

        public const byte _CONNECTED_ = (byte)'1' + 0;
        public const byte _DISCONNECTED_ = (byte)'2' + 0;
        public const byte _UNAVAILABLE_ = (byte)'3' + 0;

        public static MessageStatus CONNECTED = new MessageStatus(_CONNECTED_);
        public static MessageStatus DISCONNECTED = new MessageStatus(_DISCONNECTED_);
        public static MessageStatus UNAVAILABLE = new MessageStatus(_UNAVAILABLE_);

        public override string ToString()
        {
            if (this == CONNECTED) return "CONNECTED";
            if (this == DISCONNECTED) return "DISCONNECTED";
            if (this == UNAVAILABLE) return "UNAVAILABLE";
            return "<unknown>";
        }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding MessageStatus field model
    public class FieldModelMessageStatus : FieldModelValueType<MessageStatus>
    {
        public FieldModelMessageStatus(Buffer buffer, long offset) : base(buffer, offset) {}

        // Get the field size
        public override long FBESize => 1;

        // Clone the field model
        public override FieldModelValueType<MessageStatus> Clone() { return new FieldModelMessageStatus(_buffer, _offset); }

        // Get the value
        public override void Get(out MessageStatus value) { Get(out value, MessageStatus.Default); }
        public override void Get(out MessageStatus value, MessageStatus defaults)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
            {
                value = defaults;
                return;
            }

            value = new MessageStatus((byte)ReadUInt8(FBEOffset));
        }

        // Set the value
        public override void Set(MessageStatus value)
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return;

            Write(FBEOffset, value.Value);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct Signature : IComparable, IComparable<Signature>, IEquatable<Signature>
    {
        public byte Value { get; internal set; }

        public Signature(byte value) : this()
        {
            Value = value;
        }

        public Signature(Signature value) : this()
        {
            Value = value.Value;
        }

        public int CompareTo(object other)
        {
            return Value.CompareTo(((Signature)other).Value);
        }

        public int CompareTo(Signature other)
        {
            return Value.CompareTo(other.Value);
        }

        public override bool Equals(object other)
        {
            return (other is Signature value) && Value.Equals(value.Value);
        }

        public bool Equals(Signature other)
        {
            return Value.Equals(other.Value);
        }

        public override int GetHashCode()
        {
            return Value.GetHashCode();
        }

        public static bool operator==(Signature value1, Signature value2)
        {
            return value1.Value == value2.Value;
        }

        public static bool operator!=(Signature value1, Signature value2)
        {
            return value1.Value != value2.Value;
        }

        public static Signature Default => new Signature();

        public static FBE.FieldModelValueType<Signature> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelSignature(buffer, offset); }

        public const byte _FIXHUB_ = (byte)'1' + 0;
        public const byte _FIXMONITOR_ = (byte)'2' + 0;

        public static Signature FIXHUB = new Signature(_FIXHUB_);
        public static Signature FIXMONITOR = new Signature(_FIXMONITOR_);

        public override string ToString()
        {
            if (this == FIXHUB) return "FIXHUB";
            if (this == FIXMONITOR) return "FIXMONITOR";
            return "<unknown>";
        }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Signature field model
    public class FieldModelSignature : FieldModelValueType<Signature>
    {
        public FieldModelSignature(Buffer buffer, long offset) : base(buffer, offset) {}

        // Get the field size
        public override long FBESize => 1;

        // Clone the field model
        public override FieldModelValueType<Signature> Clone() { return new FieldModelSignature(_buffer, _offset); }

        // Get the value
        public override void Get(out Signature value) { Get(out value, Signature.Default); }
        public override void Get(out Signature value, Signature defaults)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
            {
                value = defaults;
                return;
            }

            value = new Signature((byte)ReadUInt8(FBEOffset));
        }

        // Set the value
        public override void Set(Signature value)
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return;

            Write(FBEOffset, value.Value);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct Header : IComparable, IComparable<Header>, IEquatable<Header>
    {
        public string ConnectionID;
        public MessageStatus Status;
        public string SenderID;
        public string TargetID;
        public ulong InSecNum;
        public ulong OutSecNum;
        public Action Action;
        public Signature Signature;

        public const long FBETypeConst = 1;
        public long FBEType => FBETypeConst;

        public static Header Default => new Header
        {
            ConnectionID = ""
            , Status = global::proto.MessageStatus.Default
            , SenderID = ""
            , TargetID = ""
            , InSecNum = (ulong)0UL
            , OutSecNum = (ulong)0UL
            , Action = global::proto.Action.Default
            , Signature = global::proto.Signature.Default
        };

        public Header(string ConnectionID, MessageStatus Status, string SenderID, string TargetID, ulong InSecNum, ulong OutSecNum, Action Action, Signature Signature)
        {
            this.ConnectionID = ConnectionID;
            this.Status = Status;
            this.SenderID = SenderID;
            this.TargetID = TargetID;
            this.InSecNum = InSecNum;
            this.OutSecNum = OutSecNum;
            this.Action = Action;
            this.Signature = Signature;
        }

        public Header Clone()
        {
            // Serialize the struct to the FBE stream
            var writer = new FBE.proto.HeaderModel();
            writer.Serialize(this);

            // Deserialize the struct from the FBE stream
            var reader = new FBE.proto.HeaderModel();
            reader.Attach(writer.Buffer);
            reader.Deserialize(out var result);
            return result;
        }

        public int CompareTo(object other)
        {
            int result = 0;
            return result;
        }

        public int CompareTo(Header other)
        {
            int result = 0;
            return result;
        }

        public override bool Equals(object other)
        {
            if (!(other is Header))
                return false;
            return true;
        }

        public bool Equals(Header other)
        {
            return true;
        }

        public override int GetHashCode()
        {
            int hash = 17;
            return hash;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("Header(");
            sb.Append("ConnectionID="); if (ConnectionID != null) sb.Append("\"").Append(ConnectionID).Append("\""); else sb.Append("null");
            sb.Append(",Status="); sb.Append(Status);
            sb.Append(",SenderID="); if (SenderID != null) sb.Append("\"").Append(SenderID).Append("\""); else sb.Append("null");
            sb.Append(",TargetID="); if (TargetID != null) sb.Append("\"").Append(TargetID).Append("\""); else sb.Append("null");
            sb.Append(",InSecNum="); sb.Append(InSecNum);
            sb.Append(",OutSecNum="); sb.Append(OutSecNum);
            sb.Append(",Action="); sb.Append(Action);
            sb.Append(",Signature="); sb.Append(Signature);
            sb.Append(")");
            return sb.ToString();
        }

        public static FBE.FieldModelValueType<Header> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelHeader(buffer, offset); }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Header field model
    public class FieldModelHeader : FieldModelValueType<Header>
    {
        public readonly FieldModelReferenceType<string> ConnectionID;
        public readonly FieldModelMessageStatus Status;
        public readonly FieldModelReferenceType<string> SenderID;
        public readonly FieldModelReferenceType<string> TargetID;
        public readonly FieldModelValueType<ulong> InSecNum;
        public readonly FieldModelValueType<ulong> OutSecNum;
        public readonly FieldModelAction Action;
        public readonly FieldModelSignature Signature;

        public FieldModelHeader(Buffer buffer, long offset) : base(buffer, offset)
        {
            ConnectionID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, 4 + 4);
            Status = new FieldModelMessageStatus(buffer, ConnectionID.FBEOffset + ConnectionID.FBESize);
            SenderID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, Status.FBEOffset + Status.FBESize);
            TargetID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, SenderID.FBEOffset + SenderID.FBESize);
            InSecNum = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, TargetID.FBEOffset + TargetID.FBESize);
            OutSecNum = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, InSecNum.FBEOffset + InSecNum.FBESize);
            Action = new FieldModelAction(buffer, OutSecNum.FBEOffset + OutSecNum.FBESize);
            Signature = new FieldModelSignature(buffer, Action.FBEOffset + Action.FBESize);
        }

        // Get the field size
        public override long FBESize => 4;
        // Get the field body size
        public long FBEBody
        {
            get
            {
                long fbeResult = 4 + 4
                    + ConnectionID.FBESize
                    + Status.FBESize
                    + SenderID.FBESize
                    + TargetID.FBESize
                    + InSecNum.FBESize
                    + OutSecNum.FBESize
                    + Action.FBESize
                    + Signature.FBESize
                    ;
                return fbeResult;
            }
        }
        // Get the field extra size
        public override long FBEExtra
        {
            get
            {
                if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                    return 0;

                uint fbeStructOffset = ReadUInt32(FBEOffset);
                if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4) > _buffer.Size))
                    return 0;

                _buffer.Shift(fbeStructOffset);

                long fbeResult = FBEBody
                    + ConnectionID.FBEExtra
                    + Status.FBEExtra
                    + SenderID.FBEExtra
                    + TargetID.FBEExtra
                    + InSecNum.FBEExtra
                    + OutSecNum.FBEExtra
                    + Action.FBEExtra
                    + Signature.FBEExtra
                    ;

                _buffer.Unshift(fbeStructOffset);

                return fbeResult;
            }
        }
        // Get the field type
        public const long FBETypeConst = 1;
        public long FBEType => FBETypeConst;

        // Clone the field model
        public override FieldModelValueType<Header> Clone() { return new FieldModelHeader(_buffer, _offset); }

        // Check if the struct value is valid
        public override bool Verify() { return Verify(true); }
        public bool Verify(bool fbeVerifyType)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return true;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return false;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            if (fbeStructSize < (4 + 4))
                return false;

            uint fbeStructType = ReadUInt32(fbeStructOffset + 4);
            if (fbeVerifyType && (fbeStructType != FBEType))
                return false;

            _buffer.Shift(fbeStructOffset);
            bool fbeResult = VerifyFields(fbeStructSize);
            _buffer.Unshift(fbeStructOffset);
            return fbeResult;
        }

        // Check if the struct fields are valid
        public bool VerifyFields(long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            if ((fbeCurrentSize + ConnectionID.FBESize) > fbeStructSize)
                return true;
            if (!ConnectionID.Verify())
                return false;
            fbeCurrentSize += ConnectionID.FBESize;

            if ((fbeCurrentSize + Status.FBESize) > fbeStructSize)
                return true;
            if (!Status.Verify())
                return false;
            fbeCurrentSize += Status.FBESize;

            if ((fbeCurrentSize + SenderID.FBESize) > fbeStructSize)
                return true;
            if (!SenderID.Verify())
                return false;
            fbeCurrentSize += SenderID.FBESize;

            if ((fbeCurrentSize + TargetID.FBESize) > fbeStructSize)
                return true;
            if (!TargetID.Verify())
                return false;
            fbeCurrentSize += TargetID.FBESize;

            if ((fbeCurrentSize + InSecNum.FBESize) > fbeStructSize)
                return true;
            if (!InSecNum.Verify())
                return false;
            fbeCurrentSize += InSecNum.FBESize;

            if ((fbeCurrentSize + OutSecNum.FBESize) > fbeStructSize)
                return true;
            if (!OutSecNum.Verify())
                return false;
            fbeCurrentSize += OutSecNum.FBESize;

            if ((fbeCurrentSize + Action.FBESize) > fbeStructSize)
                return true;
            if (!Action.Verify())
                return false;
            fbeCurrentSize += Action.FBESize;

            if ((fbeCurrentSize + Signature.FBESize) > fbeStructSize)
                return true;
            if (!Signature.Verify())
                return false;
            fbeCurrentSize += Signature.FBESize;

            return true;
        }

        // Get the struct value (begin phase)
        public long GetBegin()
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + 4 + 4) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return 0;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            Debug.Assert((fbeStructSize >= (4 + 4)), "Model is broken!");
            if (fbeStructSize < (4 + 4))
                return 0;

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Get the struct value (end phase)
        public void GetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Get the struct value
        public override void Get(out Header fbeValue) { Get(out fbeValue, Header.Default); }
        public override void Get(out Header fbeValue, Header defaults)
        {
            long fbeBegin = GetBegin();
            if (fbeBegin == 0)
            {
                fbeValue = defaults;
                return;
            }

            uint fbeStructSize = ReadUInt32(0);
            GetFields(out fbeValue, fbeStructSize);
            GetEnd(fbeBegin);
        }

        // Get the struct fields values
        public void GetFields(out Header fbeValue, long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            fbeValue = Header.Default;

            if ((fbeCurrentSize + ConnectionID.FBESize) <= fbeStructSize)
                ConnectionID.Get(out fbeValue.ConnectionID);
            else
                fbeValue.ConnectionID = "";
            fbeCurrentSize += ConnectionID.FBESize;

            if ((fbeCurrentSize + Status.FBESize) <= fbeStructSize)
                Status.Get(out fbeValue.Status);
            else
                fbeValue.Status = global::proto.MessageStatus.Default;
            fbeCurrentSize += Status.FBESize;

            if ((fbeCurrentSize + SenderID.FBESize) <= fbeStructSize)
                SenderID.Get(out fbeValue.SenderID);
            else
                fbeValue.SenderID = "";
            fbeCurrentSize += SenderID.FBESize;

            if ((fbeCurrentSize + TargetID.FBESize) <= fbeStructSize)
                TargetID.Get(out fbeValue.TargetID);
            else
                fbeValue.TargetID = "";
            fbeCurrentSize += TargetID.FBESize;

            if ((fbeCurrentSize + InSecNum.FBESize) <= fbeStructSize)
                InSecNum.Get(out fbeValue.InSecNum);
            else
                fbeValue.InSecNum = (ulong)0UL;
            fbeCurrentSize += InSecNum.FBESize;

            if ((fbeCurrentSize + OutSecNum.FBESize) <= fbeStructSize)
                OutSecNum.Get(out fbeValue.OutSecNum);
            else
                fbeValue.OutSecNum = (ulong)0UL;
            fbeCurrentSize += OutSecNum.FBESize;

            if ((fbeCurrentSize + Action.FBESize) <= fbeStructSize)
                Action.Get(out fbeValue.Action);
            else
                fbeValue.Action = global::proto.Action.Default;
            fbeCurrentSize += Action.FBESize;

            if ((fbeCurrentSize + Signature.FBESize) <= fbeStructSize)
                Signature.Get(out fbeValue.Signature);
            else
                fbeValue.Signature = global::proto.Signature.Default;
            fbeCurrentSize += Signature.FBESize;
        }

        // Set the struct value (begin phase)
        public long SetBegin()
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructSize = (uint)FBEBody;
            uint fbeStructOffset = (uint)(_buffer.Allocate(fbeStructSize) - _buffer.Offset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + fbeStructSize) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + fbeStructSize) > _buffer.Size))
                return 0;

            Write(FBEOffset, fbeStructOffset);
            Write(fbeStructOffset, fbeStructSize);
            Write(fbeStructOffset + 4, (uint)FBEType);

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Set the struct value (end phase)
        public void SetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Set the struct value
        public override void Set(Header fbeValue)
        {
            long fbeBegin = SetBegin();
            if (fbeBegin == 0)
                return;

            SetFields(fbeValue);
            SetEnd(fbeBegin);
        }

        // Set the struct fields values
        public void SetFields(Header fbeValue)
        {
            ConnectionID.Set(fbeValue.ConnectionID);
            Status.Set(fbeValue.Status);
            SenderID.Set(fbeValue.SenderID);
            TargetID.Set(fbeValue.TargetID);
            InSecNum.Set(fbeValue.InSecNum);
            OutSecNum.Set(fbeValue.OutSecNum);
            Action.Set(fbeValue.Action);
            Signature.Set(fbeValue.Signature);
        }
    }

} // namespace proto
} // namespace FBE

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Header model
    public class HeaderModel : Model
    {
        public readonly FieldModelHeader model;

        public HeaderModel() { model = new FieldModelHeader(Buffer, 4); }
        public HeaderModel(Buffer buffer) : base(buffer) { model = new FieldModelHeader(Buffer, 4); }

        // Get the model size
        public long FBESize => model.FBESize + model.FBEExtra;
        // Get the model type
        public const long FBETypeConst = FieldModelHeader.FBETypeConst;
        public long FBEType => FBETypeConst;

        // Check if the struct value is valid
        public bool Verify()
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
                return false;

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            if (fbeFullSize < model.FBESize)
                return false;

            return model.Verify();
        }

        // Create a new model (begin phase)
        public long CreateBegin()
        {
            long fbeBegin = Buffer.Allocate(4 + model.FBESize);
            return fbeBegin;
        }

        // Create a new model (end phase)
        public long CreateEnd(long fbeBegin)
        {
            long fbeEnd = Buffer.Size;
            uint fbeFullSize = (uint)(fbeEnd - fbeBegin);
            Write(model.FBEOffset - 4, fbeFullSize);
            return fbeFullSize;
        }

        // Serialize the struct value
        public long Serialize(Header value)
        {
            long fbeBegin = CreateBegin();
            model.Set(value);
            long fbeFullSize = CreateEnd(fbeBegin);
            return fbeFullSize;
        }

        // Deserialize the struct value
        public long Deserialize(out Header value)
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
            {
                value = Header.Default;
                return 0;
            }

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            Debug.Assert((fbeFullSize >= model.FBESize), "Model is broken!");
            if (fbeFullSize < model.FBESize)
            {
                value = Header.Default;
                return 0;
            }

            model.Get(out value);
            return fbeFullSize;
        }

        // Move to the next struct value
        public void Next(long prev)
        {
            model.FBEShift(prev);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct Body : IComparable, IComparable<Body>, IEquatable<Body>
    {
        public string FIXMessage;
        public string MessageType;
        public string SendingTime;
        public string ConnectionID;

        public const long FBETypeConst = 2;
        public long FBEType => FBETypeConst;

        public static Body Default => new Body
        {
            FIXMessage = ""
            , MessageType = ""
            , SendingTime = ""
            , ConnectionID = ""
        };

        public Body(string FIXMessage, string MessageType, string SendingTime, string ConnectionID)
        {
            this.FIXMessage = FIXMessage;
            this.MessageType = MessageType;
            this.SendingTime = SendingTime;
            this.ConnectionID = ConnectionID;
        }

        public Body Clone()
        {
            // Serialize the struct to the FBE stream
            var writer = new FBE.proto.BodyModel();
            writer.Serialize(this);

            // Deserialize the struct from the FBE stream
            var reader = new FBE.proto.BodyModel();
            reader.Attach(writer.Buffer);
            reader.Deserialize(out var result);
            return result;
        }

        public int CompareTo(object other)
        {
            int result = 0;
            return result;
        }

        public int CompareTo(Body other)
        {
            int result = 0;
            return result;
        }

        public override bool Equals(object other)
        {
            if (!(other is Body))
                return false;
            return true;
        }

        public bool Equals(Body other)
        {
            return true;
        }

        public override int GetHashCode()
        {
            int hash = 17;
            return hash;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("Body(");
            sb.Append("FIXMessage="); if (FIXMessage != null) sb.Append("\"").Append(FIXMessage).Append("\""); else sb.Append("null");
            sb.Append(",MessageType="); if (MessageType != null) sb.Append("\"").Append(MessageType).Append("\""); else sb.Append("null");
            sb.Append(",SendingTime="); if (SendingTime != null) sb.Append("\"").Append(SendingTime).Append("\""); else sb.Append("null");
            sb.Append(",ConnectionID="); if (ConnectionID != null) sb.Append("\"").Append(ConnectionID).Append("\""); else sb.Append("null");
            sb.Append(")");
            return sb.ToString();
        }

        public static FBE.FieldModelValueType<Body> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelBody(buffer, offset); }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Body field model
    public class FieldModelBody : FieldModelValueType<Body>
    {
        public readonly FieldModelReferenceType<string> FIXMessage;
        public readonly FieldModelReferenceType<string> MessageType;
        public readonly FieldModelReferenceType<string> SendingTime;
        public readonly FieldModelReferenceType<string> ConnectionID;

        public FieldModelBody(Buffer buffer, long offset) : base(buffer, offset)
        {
            FIXMessage = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, 4 + 4);
            MessageType = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, FIXMessage.FBEOffset + FIXMessage.FBESize);
            SendingTime = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, MessageType.FBEOffset + MessageType.FBESize);
            ConnectionID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, SendingTime.FBEOffset + SendingTime.FBESize);
        }

        // Get the field size
        public override long FBESize => 4;
        // Get the field body size
        public long FBEBody
        {
            get
            {
                long fbeResult = 4 + 4
                    + FIXMessage.FBESize
                    + MessageType.FBESize
                    + SendingTime.FBESize
                    + ConnectionID.FBESize
                    ;
                return fbeResult;
            }
        }
        // Get the field extra size
        public override long FBEExtra
        {
            get
            {
                if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                    return 0;

                uint fbeStructOffset = ReadUInt32(FBEOffset);
                if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4) > _buffer.Size))
                    return 0;

                _buffer.Shift(fbeStructOffset);

                long fbeResult = FBEBody
                    + FIXMessage.FBEExtra
                    + MessageType.FBEExtra
                    + SendingTime.FBEExtra
                    + ConnectionID.FBEExtra
                    ;

                _buffer.Unshift(fbeStructOffset);

                return fbeResult;
            }
        }
        // Get the field type
        public const long FBETypeConst = 2;
        public long FBEType => FBETypeConst;

        // Clone the field model
        public override FieldModelValueType<Body> Clone() { return new FieldModelBody(_buffer, _offset); }

        // Check if the struct value is valid
        public override bool Verify() { return Verify(true); }
        public bool Verify(bool fbeVerifyType)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return true;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return false;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            if (fbeStructSize < (4 + 4))
                return false;

            uint fbeStructType = ReadUInt32(fbeStructOffset + 4);
            if (fbeVerifyType && (fbeStructType != FBEType))
                return false;

            _buffer.Shift(fbeStructOffset);
            bool fbeResult = VerifyFields(fbeStructSize);
            _buffer.Unshift(fbeStructOffset);
            return fbeResult;
        }

        // Check if the struct fields are valid
        public bool VerifyFields(long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            if ((fbeCurrentSize + FIXMessage.FBESize) > fbeStructSize)
                return true;
            if (!FIXMessage.Verify())
                return false;
            fbeCurrentSize += FIXMessage.FBESize;

            if ((fbeCurrentSize + MessageType.FBESize) > fbeStructSize)
                return true;
            if (!MessageType.Verify())
                return false;
            fbeCurrentSize += MessageType.FBESize;

            if ((fbeCurrentSize + SendingTime.FBESize) > fbeStructSize)
                return true;
            if (!SendingTime.Verify())
                return false;
            fbeCurrentSize += SendingTime.FBESize;

            if ((fbeCurrentSize + ConnectionID.FBESize) > fbeStructSize)
                return true;
            if (!ConnectionID.Verify())
                return false;
            fbeCurrentSize += ConnectionID.FBESize;

            return true;
        }

        // Get the struct value (begin phase)
        public long GetBegin()
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + 4 + 4) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return 0;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            Debug.Assert((fbeStructSize >= (4 + 4)), "Model is broken!");
            if (fbeStructSize < (4 + 4))
                return 0;

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Get the struct value (end phase)
        public void GetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Get the struct value
        public override void Get(out Body fbeValue) { Get(out fbeValue, Body.Default); }
        public override void Get(out Body fbeValue, Body defaults)
        {
            long fbeBegin = GetBegin();
            if (fbeBegin == 0)
            {
                fbeValue = defaults;
                return;
            }

            uint fbeStructSize = ReadUInt32(0);
            GetFields(out fbeValue, fbeStructSize);
            GetEnd(fbeBegin);
        }

        // Get the struct fields values
        public void GetFields(out Body fbeValue, long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            fbeValue = Body.Default;

            if ((fbeCurrentSize + FIXMessage.FBESize) <= fbeStructSize)
                FIXMessage.Get(out fbeValue.FIXMessage);
            else
                fbeValue.FIXMessage = "";
            fbeCurrentSize += FIXMessage.FBESize;

            if ((fbeCurrentSize + MessageType.FBESize) <= fbeStructSize)
                MessageType.Get(out fbeValue.MessageType);
            else
                fbeValue.MessageType = "";
            fbeCurrentSize += MessageType.FBESize;

            if ((fbeCurrentSize + SendingTime.FBESize) <= fbeStructSize)
                SendingTime.Get(out fbeValue.SendingTime);
            else
                fbeValue.SendingTime = "";
            fbeCurrentSize += SendingTime.FBESize;

            if ((fbeCurrentSize + ConnectionID.FBESize) <= fbeStructSize)
                ConnectionID.Get(out fbeValue.ConnectionID);
            else
                fbeValue.ConnectionID = "";
            fbeCurrentSize += ConnectionID.FBESize;
        }

        // Set the struct value (begin phase)
        public long SetBegin()
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructSize = (uint)FBEBody;
            uint fbeStructOffset = (uint)(_buffer.Allocate(fbeStructSize) - _buffer.Offset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + fbeStructSize) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + fbeStructSize) > _buffer.Size))
                return 0;

            Write(FBEOffset, fbeStructOffset);
            Write(fbeStructOffset, fbeStructSize);
            Write(fbeStructOffset + 4, (uint)FBEType);

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Set the struct value (end phase)
        public void SetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Set the struct value
        public override void Set(Body fbeValue)
        {
            long fbeBegin = SetBegin();
            if (fbeBegin == 0)
                return;

            SetFields(fbeValue);
            SetEnd(fbeBegin);
        }

        // Set the struct fields values
        public void SetFields(Body fbeValue)
        {
            FIXMessage.Set(fbeValue.FIXMessage);
            MessageType.Set(fbeValue.MessageType);
            SendingTime.Set(fbeValue.SendingTime);
            ConnectionID.Set(fbeValue.ConnectionID);
        }
    }

} // namespace proto
} // namespace FBE

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Body model
    public class BodyModel : Model
    {
        public readonly FieldModelBody model;

        public BodyModel() { model = new FieldModelBody(Buffer, 4); }
        public BodyModel(Buffer buffer) : base(buffer) { model = new FieldModelBody(Buffer, 4); }

        // Get the model size
        public long FBESize => model.FBESize + model.FBEExtra;
        // Get the model type
        public const long FBETypeConst = FieldModelBody.FBETypeConst;
        public long FBEType => FBETypeConst;

        // Check if the struct value is valid
        public bool Verify()
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
                return false;

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            if (fbeFullSize < model.FBESize)
                return false;

            return model.Verify();
        }

        // Create a new model (begin phase)
        public long CreateBegin()
        {
            long fbeBegin = Buffer.Allocate(4 + model.FBESize);
            return fbeBegin;
        }

        // Create a new model (end phase)
        public long CreateEnd(long fbeBegin)
        {
            long fbeEnd = Buffer.Size;
            uint fbeFullSize = (uint)(fbeEnd - fbeBegin);
            Write(model.FBEOffset - 4, fbeFullSize);
            return fbeFullSize;
        }

        // Serialize the struct value
        public long Serialize(Body value)
        {
            long fbeBegin = CreateBegin();
            model.Set(value);
            long fbeFullSize = CreateEnd(fbeBegin);
            return fbeFullSize;
        }

        // Deserialize the struct value
        public long Deserialize(out Body value)
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
            {
                value = Body.Default;
                return 0;
            }

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            Debug.Assert((fbeFullSize >= model.FBESize), "Model is broken!");
            if (fbeFullSize < model.FBESize)
            {
                value = Body.Default;
                return 0;
            }

            model.Get(out value);
            return fbeFullSize;
        }

        // Move to the next struct value
        public void Next(long prev)
        {
            model.FBEShift(prev);
        }
    }

} // namespace proto
} // namespace FBE

namespace proto {

    public struct Config : IComparable, IComparable<Config>, IEquatable<Config>
    {
        public string ConnectionID;
        public MessageStatus Status;
        public string SenderCompID;
        public string TargetCompID;
        public string IPAddress;
        public string BackUpIPAddress;
        public ulong Port;
        public ulong BackUpPort;
        public string Validate;
        public string HandleResend;
        public ulong HeartBeatInterval;
        public ulong MaxLatency;
        public ulong ResetConnection;
        public ulong EnableConnection;
        public string FIXVersion;
        public string InternalFIXVersion;
        public string Mode;
        public ulong DBEnabled;
        public ulong LatencyEnabled;
        public ulong AutoConnect;
        public ulong AutoReconnect;
        public ulong ReconnectDelay;
        public ulong ConnectRetry;
        public string LogonRawData;
        public ulong MilliSecondTime;
        public ulong QEnabled;
        public string SessionStart;
        public string SessionEnd;
        public string TaskReset;
        public ulong InSecNum;
        public ulong OutSecNum;
        public string LastUpdated;

        public const long FBETypeConst = 3;
        public long FBEType => FBETypeConst;

        public static Config Default => new Config
        {
            ConnectionID = ""
            , Status = global::proto.MessageStatus.Default
            , SenderCompID = ""
            , TargetCompID = ""
            , IPAddress = ""
            , BackUpIPAddress = ""
            , Port = (ulong)0UL
            , BackUpPort = (ulong)0UL
            , Validate = ""
            , HandleResend = ""
            , HeartBeatInterval = (ulong)0UL
            , MaxLatency = (ulong)0UL
            , ResetConnection = (ulong)0UL
            , EnableConnection = (ulong)0UL
            , FIXVersion = ""
            , InternalFIXVersion = ""
            , Mode = ""
            , DBEnabled = (ulong)0UL
            , LatencyEnabled = (ulong)0UL
            , AutoConnect = (ulong)0UL
            , AutoReconnect = (ulong)0UL
            , ReconnectDelay = (ulong)0UL
            , ConnectRetry = (ulong)0UL
            , LogonRawData = ""
            , MilliSecondTime = (ulong)0UL
            , QEnabled = (ulong)0UL
            , SessionStart = ""
            , SessionEnd = ""
            , TaskReset = ""
            , InSecNum = (ulong)0UL
            , OutSecNum = (ulong)0UL
            , LastUpdated = ""
        };

        public Config(string ConnectionID, MessageStatus Status, string SenderCompID, string TargetCompID, string IPAddress, string BackUpIPAddress, ulong Port, ulong BackUpPort, string Validate, string HandleResend, ulong HeartBeatInterval, ulong MaxLatency, ulong ResetConnection, ulong EnableConnection, string FIXVersion, string InternalFIXVersion, string Mode, ulong DBEnabled, ulong LatencyEnabled, ulong AutoConnect, ulong AutoReconnect, ulong ReconnectDelay, ulong ConnectRetry, string LogonRawData, ulong MilliSecondTime, ulong QEnabled, string SessionStart, string SessionEnd, string TaskReset, ulong InSecNum, ulong OutSecNum, string LastUpdated)
        {
            this.ConnectionID = ConnectionID;
            this.Status = Status;
            this.SenderCompID = SenderCompID;
            this.TargetCompID = TargetCompID;
            this.IPAddress = IPAddress;
            this.BackUpIPAddress = BackUpIPAddress;
            this.Port = Port;
            this.BackUpPort = BackUpPort;
            this.Validate = Validate;
            this.HandleResend = HandleResend;
            this.HeartBeatInterval = HeartBeatInterval;
            this.MaxLatency = MaxLatency;
            this.ResetConnection = ResetConnection;
            this.EnableConnection = EnableConnection;
            this.FIXVersion = FIXVersion;
            this.InternalFIXVersion = InternalFIXVersion;
            this.Mode = Mode;
            this.DBEnabled = DBEnabled;
            this.LatencyEnabled = LatencyEnabled;
            this.AutoConnect = AutoConnect;
            this.AutoReconnect = AutoReconnect;
            this.ReconnectDelay = ReconnectDelay;
            this.ConnectRetry = ConnectRetry;
            this.LogonRawData = LogonRawData;
            this.MilliSecondTime = MilliSecondTime;
            this.QEnabled = QEnabled;
            this.SessionStart = SessionStart;
            this.SessionEnd = SessionEnd;
            this.TaskReset = TaskReset;
            this.InSecNum = InSecNum;
            this.OutSecNum = OutSecNum;
            this.LastUpdated = LastUpdated;
        }

        public Config Clone()
        {
            // Serialize the struct to the FBE stream
            var writer = new FBE.proto.ConfigModel();
            writer.Serialize(this);

            // Deserialize the struct from the FBE stream
            var reader = new FBE.proto.ConfigModel();
            reader.Attach(writer.Buffer);
            reader.Deserialize(out var result);
            return result;
        }

        public int CompareTo(object other)
        {
            int result = 0;
            return result;
        }

        public int CompareTo(Config other)
        {
            int result = 0;
            return result;
        }

        public override bool Equals(object other)
        {
            if (!(other is Config))
                return false;
            return true;
        }

        public bool Equals(Config other)
        {
            return true;
        }

        public override int GetHashCode()
        {
            int hash = 17;
            return hash;
        }

        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("Config(");
            sb.Append("ConnectionID="); if (ConnectionID != null) sb.Append("\"").Append(ConnectionID).Append("\""); else sb.Append("null");
            sb.Append(",Status="); sb.Append(Status);
            sb.Append(",SenderCompID="); if (SenderCompID != null) sb.Append("\"").Append(SenderCompID).Append("\""); else sb.Append("null");
            sb.Append(",TargetCompID="); if (TargetCompID != null) sb.Append("\"").Append(TargetCompID).Append("\""); else sb.Append("null");
            sb.Append(",IPAddress="); if (IPAddress != null) sb.Append("\"").Append(IPAddress).Append("\""); else sb.Append("null");
            sb.Append(",BackUpIPAddress="); if (BackUpIPAddress != null) sb.Append("\"").Append(BackUpIPAddress).Append("\""); else sb.Append("null");
            sb.Append(",Port="); sb.Append(Port);
            sb.Append(",BackUpPort="); sb.Append(BackUpPort);
            sb.Append(",Validate="); if (Validate != null) sb.Append("\"").Append(Validate).Append("\""); else sb.Append("null");
            sb.Append(",HandleResend="); if (HandleResend != null) sb.Append("\"").Append(HandleResend).Append("\""); else sb.Append("null");
            sb.Append(",HeartBeatInterval="); sb.Append(HeartBeatInterval);
            sb.Append(",MaxLatency="); sb.Append(MaxLatency);
            sb.Append(",ResetConnection="); sb.Append(ResetConnection);
            sb.Append(",EnableConnection="); sb.Append(EnableConnection);
            sb.Append(",FIXVersion="); if (FIXVersion != null) sb.Append("\"").Append(FIXVersion).Append("\""); else sb.Append("null");
            sb.Append(",InternalFIXVersion="); if (InternalFIXVersion != null) sb.Append("\"").Append(InternalFIXVersion).Append("\""); else sb.Append("null");
            sb.Append(",Mode="); if (Mode != null) sb.Append("\"").Append(Mode).Append("\""); else sb.Append("null");
            sb.Append(",DBEnabled="); sb.Append(DBEnabled);
            sb.Append(",LatencyEnabled="); sb.Append(LatencyEnabled);
            sb.Append(",AutoConnect="); sb.Append(AutoConnect);
            sb.Append(",AutoReconnect="); sb.Append(AutoReconnect);
            sb.Append(",ReconnectDelay="); sb.Append(ReconnectDelay);
            sb.Append(",ConnectRetry="); sb.Append(ConnectRetry);
            sb.Append(",LogonRawData="); if (LogonRawData != null) sb.Append("\"").Append(LogonRawData).Append("\""); else sb.Append("null");
            sb.Append(",MilliSecondTime="); sb.Append(MilliSecondTime);
            sb.Append(",QEnabled="); sb.Append(QEnabled);
            sb.Append(",SessionStart="); if (SessionStart != null) sb.Append("\"").Append(SessionStart).Append("\""); else sb.Append("null");
            sb.Append(",SessionEnd="); if (SessionEnd != null) sb.Append("\"").Append(SessionEnd).Append("\""); else sb.Append("null");
            sb.Append(",TaskReset="); if (TaskReset != null) sb.Append("\"").Append(TaskReset).Append("\""); else sb.Append("null");
            sb.Append(",InSecNum="); sb.Append(InSecNum);
            sb.Append(",OutSecNum="); sb.Append(OutSecNum);
            sb.Append(",LastUpdated="); if (LastUpdated != null) sb.Append("\"").Append(LastUpdated).Append("\""); else sb.Append("null");
            sb.Append(")");
            return sb.ToString();
        }

        public static FBE.FieldModelValueType<Config> CreateFieldModel(FBE.Buffer buffer, long offset) { return new FBE.proto.FieldModelConfig(buffer, offset); }
    }

} // namespace proto

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Config field model
    public class FieldModelConfig : FieldModelValueType<Config>
    {
        public readonly FieldModelReferenceType<string> ConnectionID;
        public readonly FieldModelMessageStatus Status;
        public readonly FieldModelReferenceType<string> SenderCompID;
        public readonly FieldModelReferenceType<string> TargetCompID;
        public readonly FieldModelReferenceType<string> IPAddress;
        public readonly FieldModelReferenceType<string> BackUpIPAddress;
        public readonly FieldModelValueType<ulong> Port;
        public readonly FieldModelValueType<ulong> BackUpPort;
        public readonly FieldModelReferenceType<string> Validate;
        public readonly FieldModelReferenceType<string> HandleResend;
        public readonly FieldModelValueType<ulong> HeartBeatInterval;
        public readonly FieldModelValueType<ulong> MaxLatency;
        public readonly FieldModelValueType<ulong> ResetConnection;
        public readonly FieldModelValueType<ulong> EnableConnection;
        public readonly FieldModelReferenceType<string> FIXVersion;
        public readonly FieldModelReferenceType<string> InternalFIXVersion;
        public readonly FieldModelReferenceType<string> Mode;
        public readonly FieldModelValueType<ulong> DBEnabled;
        public readonly FieldModelValueType<ulong> LatencyEnabled;
        public readonly FieldModelValueType<ulong> AutoConnect;
        public readonly FieldModelValueType<ulong> AutoReconnect;
        public readonly FieldModelValueType<ulong> ReconnectDelay;
        public readonly FieldModelValueType<ulong> ConnectRetry;
        public readonly FieldModelReferenceType<string> LogonRawData;
        public readonly FieldModelValueType<ulong> MilliSecondTime;
        public readonly FieldModelValueType<ulong> QEnabled;
        public readonly FieldModelReferenceType<string> SessionStart;
        public readonly FieldModelReferenceType<string> SessionEnd;
        public readonly FieldModelReferenceType<string> TaskReset;
        public readonly FieldModelValueType<ulong> InSecNum;
        public readonly FieldModelValueType<ulong> OutSecNum;
        public readonly FieldModelReferenceType<string> LastUpdated;

        public FieldModelConfig(Buffer buffer, long offset) : base(buffer, offset)
        {
            ConnectionID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, 4 + 4);
            Status = new FieldModelMessageStatus(buffer, ConnectionID.FBEOffset + ConnectionID.FBESize);
            SenderCompID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, Status.FBEOffset + Status.FBESize);
            TargetCompID = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, SenderCompID.FBEOffset + SenderCompID.FBESize);
            IPAddress = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, TargetCompID.FBEOffset + TargetCompID.FBESize);
            BackUpIPAddress = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, IPAddress.FBEOffset + IPAddress.FBESize);
            Port = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, BackUpIPAddress.FBEOffset + BackUpIPAddress.FBESize);
            BackUpPort = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, Port.FBEOffset + Port.FBESize);
            Validate = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, BackUpPort.FBEOffset + BackUpPort.FBESize);
            HandleResend = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, Validate.FBEOffset + Validate.FBESize);
            HeartBeatInterval = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, HandleResend.FBEOffset + HandleResend.FBESize);
            MaxLatency = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, HeartBeatInterval.FBEOffset + HeartBeatInterval.FBESize);
            ResetConnection = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, MaxLatency.FBEOffset + MaxLatency.FBESize);
            EnableConnection = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, ResetConnection.FBEOffset + ResetConnection.FBESize);
            FIXVersion = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, EnableConnection.FBEOffset + EnableConnection.FBESize);
            InternalFIXVersion = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, FIXVersion.FBEOffset + FIXVersion.FBESize);
            Mode = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, InternalFIXVersion.FBEOffset + InternalFIXVersion.FBESize);
            DBEnabled = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, Mode.FBEOffset + Mode.FBESize);
            LatencyEnabled = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, DBEnabled.FBEOffset + DBEnabled.FBESize);
            AutoConnect = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, LatencyEnabled.FBEOffset + LatencyEnabled.FBESize);
            AutoReconnect = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, AutoConnect.FBEOffset + AutoConnect.FBESize);
            ReconnectDelay = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, AutoReconnect.FBEOffset + AutoReconnect.FBESize);
            ConnectRetry = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, ReconnectDelay.FBEOffset + ReconnectDelay.FBESize);
            LogonRawData = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, ConnectRetry.FBEOffset + ConnectRetry.FBESize);
            MilliSecondTime = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, LogonRawData.FBEOffset + LogonRawData.FBESize);
            QEnabled = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, MilliSecondTime.FBEOffset + MilliSecondTime.FBESize);
            SessionStart = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, QEnabled.FBEOffset + QEnabled.FBESize);
            SessionEnd = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, SessionStart.FBEOffset + SessionStart.FBESize);
            TaskReset = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, SessionEnd.FBEOffset + SessionEnd.FBESize);
            InSecNum = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, TaskReset.FBEOffset + TaskReset.FBESize);
            OutSecNum = FieldModelValueType<ulong>.CreateFieldModel(BaseTypes.UINT64, buffer, InSecNum.FBEOffset + InSecNum.FBESize);
            LastUpdated = FieldModelReferenceType<string>.CreateFieldModel(BaseTypes.STRING, buffer, OutSecNum.FBEOffset + OutSecNum.FBESize);
        }

        // Get the field size
        public override long FBESize => 4;
        // Get the field body size
        public long FBEBody
        {
            get
            {
                long fbeResult = 4 + 4
                    + ConnectionID.FBESize
                    + Status.FBESize
                    + SenderCompID.FBESize
                    + TargetCompID.FBESize
                    + IPAddress.FBESize
                    + BackUpIPAddress.FBESize
                    + Port.FBESize
                    + BackUpPort.FBESize
                    + Validate.FBESize
                    + HandleResend.FBESize
                    + HeartBeatInterval.FBESize
                    + MaxLatency.FBESize
                    + ResetConnection.FBESize
                    + EnableConnection.FBESize
                    + FIXVersion.FBESize
                    + InternalFIXVersion.FBESize
                    + Mode.FBESize
                    + DBEnabled.FBESize
                    + LatencyEnabled.FBESize
                    + AutoConnect.FBESize
                    + AutoReconnect.FBESize
                    + ReconnectDelay.FBESize
                    + ConnectRetry.FBESize
                    + LogonRawData.FBESize
                    + MilliSecondTime.FBESize
                    + QEnabled.FBESize
                    + SessionStart.FBESize
                    + SessionEnd.FBESize
                    + TaskReset.FBESize
                    + InSecNum.FBESize
                    + OutSecNum.FBESize
                    + LastUpdated.FBESize
                    ;
                return fbeResult;
            }
        }
        // Get the field extra size
        public override long FBEExtra
        {
            get
            {
                if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                    return 0;

                uint fbeStructOffset = ReadUInt32(FBEOffset);
                if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4) > _buffer.Size))
                    return 0;

                _buffer.Shift(fbeStructOffset);

                long fbeResult = FBEBody
                    + ConnectionID.FBEExtra
                    + Status.FBEExtra
                    + SenderCompID.FBEExtra
                    + TargetCompID.FBEExtra
                    + IPAddress.FBEExtra
                    + BackUpIPAddress.FBEExtra
                    + Port.FBEExtra
                    + BackUpPort.FBEExtra
                    + Validate.FBEExtra
                    + HandleResend.FBEExtra
                    + HeartBeatInterval.FBEExtra
                    + MaxLatency.FBEExtra
                    + ResetConnection.FBEExtra
                    + EnableConnection.FBEExtra
                    + FIXVersion.FBEExtra
                    + InternalFIXVersion.FBEExtra
                    + Mode.FBEExtra
                    + DBEnabled.FBEExtra
                    + LatencyEnabled.FBEExtra
                    + AutoConnect.FBEExtra
                    + AutoReconnect.FBEExtra
                    + ReconnectDelay.FBEExtra
                    + ConnectRetry.FBEExtra
                    + LogonRawData.FBEExtra
                    + MilliSecondTime.FBEExtra
                    + QEnabled.FBEExtra
                    + SessionStart.FBEExtra
                    + SessionEnd.FBEExtra
                    + TaskReset.FBEExtra
                    + InSecNum.FBEExtra
                    + OutSecNum.FBEExtra
                    + LastUpdated.FBEExtra
                    ;

                _buffer.Unshift(fbeStructOffset);

                return fbeResult;
            }
        }
        // Get the field type
        public const long FBETypeConst = 3;
        public long FBEType => FBETypeConst;

        // Clone the field model
        public override FieldModelValueType<Config> Clone() { return new FieldModelConfig(_buffer, _offset); }

        // Check if the struct value is valid
        public override bool Verify() { return Verify(true); }
        public bool Verify(bool fbeVerifyType)
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return true;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return false;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            if (fbeStructSize < (4 + 4))
                return false;

            uint fbeStructType = ReadUInt32(fbeStructOffset + 4);
            if (fbeVerifyType && (fbeStructType != FBEType))
                return false;

            _buffer.Shift(fbeStructOffset);
            bool fbeResult = VerifyFields(fbeStructSize);
            _buffer.Unshift(fbeStructOffset);
            return fbeResult;
        }

        // Check if the struct fields are valid
        public bool VerifyFields(long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            if ((fbeCurrentSize + ConnectionID.FBESize) > fbeStructSize)
                return true;
            if (!ConnectionID.Verify())
                return false;
            fbeCurrentSize += ConnectionID.FBESize;

            if ((fbeCurrentSize + Status.FBESize) > fbeStructSize)
                return true;
            if (!Status.Verify())
                return false;
            fbeCurrentSize += Status.FBESize;

            if ((fbeCurrentSize + SenderCompID.FBESize) > fbeStructSize)
                return true;
            if (!SenderCompID.Verify())
                return false;
            fbeCurrentSize += SenderCompID.FBESize;

            if ((fbeCurrentSize + TargetCompID.FBESize) > fbeStructSize)
                return true;
            if (!TargetCompID.Verify())
                return false;
            fbeCurrentSize += TargetCompID.FBESize;

            if ((fbeCurrentSize + IPAddress.FBESize) > fbeStructSize)
                return true;
            if (!IPAddress.Verify())
                return false;
            fbeCurrentSize += IPAddress.FBESize;

            if ((fbeCurrentSize + BackUpIPAddress.FBESize) > fbeStructSize)
                return true;
            if (!BackUpIPAddress.Verify())
                return false;
            fbeCurrentSize += BackUpIPAddress.FBESize;

            if ((fbeCurrentSize + Port.FBESize) > fbeStructSize)
                return true;
            if (!Port.Verify())
                return false;
            fbeCurrentSize += Port.FBESize;

            if ((fbeCurrentSize + BackUpPort.FBESize) > fbeStructSize)
                return true;
            if (!BackUpPort.Verify())
                return false;
            fbeCurrentSize += BackUpPort.FBESize;

            if ((fbeCurrentSize + Validate.FBESize) > fbeStructSize)
                return true;
            if (!Validate.Verify())
                return false;
            fbeCurrentSize += Validate.FBESize;

            if ((fbeCurrentSize + HandleResend.FBESize) > fbeStructSize)
                return true;
            if (!HandleResend.Verify())
                return false;
            fbeCurrentSize += HandleResend.FBESize;

            if ((fbeCurrentSize + HeartBeatInterval.FBESize) > fbeStructSize)
                return true;
            if (!HeartBeatInterval.Verify())
                return false;
            fbeCurrentSize += HeartBeatInterval.FBESize;

            if ((fbeCurrentSize + MaxLatency.FBESize) > fbeStructSize)
                return true;
            if (!MaxLatency.Verify())
                return false;
            fbeCurrentSize += MaxLatency.FBESize;

            if ((fbeCurrentSize + ResetConnection.FBESize) > fbeStructSize)
                return true;
            if (!ResetConnection.Verify())
                return false;
            fbeCurrentSize += ResetConnection.FBESize;

            if ((fbeCurrentSize + EnableConnection.FBESize) > fbeStructSize)
                return true;
            if (!EnableConnection.Verify())
                return false;
            fbeCurrentSize += EnableConnection.FBESize;

            if ((fbeCurrentSize + FIXVersion.FBESize) > fbeStructSize)
                return true;
            if (!FIXVersion.Verify())
                return false;
            fbeCurrentSize += FIXVersion.FBESize;

            if ((fbeCurrentSize + InternalFIXVersion.FBESize) > fbeStructSize)
                return true;
            if (!InternalFIXVersion.Verify())
                return false;
            fbeCurrentSize += InternalFIXVersion.FBESize;

            if ((fbeCurrentSize + Mode.FBESize) > fbeStructSize)
                return true;
            if (!Mode.Verify())
                return false;
            fbeCurrentSize += Mode.FBESize;

            if ((fbeCurrentSize + DBEnabled.FBESize) > fbeStructSize)
                return true;
            if (!DBEnabled.Verify())
                return false;
            fbeCurrentSize += DBEnabled.FBESize;

            if ((fbeCurrentSize + LatencyEnabled.FBESize) > fbeStructSize)
                return true;
            if (!LatencyEnabled.Verify())
                return false;
            fbeCurrentSize += LatencyEnabled.FBESize;

            if ((fbeCurrentSize + AutoConnect.FBESize) > fbeStructSize)
                return true;
            if (!AutoConnect.Verify())
                return false;
            fbeCurrentSize += AutoConnect.FBESize;

            if ((fbeCurrentSize + AutoReconnect.FBESize) > fbeStructSize)
                return true;
            if (!AutoReconnect.Verify())
                return false;
            fbeCurrentSize += AutoReconnect.FBESize;

            if ((fbeCurrentSize + ReconnectDelay.FBESize) > fbeStructSize)
                return true;
            if (!ReconnectDelay.Verify())
                return false;
            fbeCurrentSize += ReconnectDelay.FBESize;

            if ((fbeCurrentSize + ConnectRetry.FBESize) > fbeStructSize)
                return true;
            if (!ConnectRetry.Verify())
                return false;
            fbeCurrentSize += ConnectRetry.FBESize;

            if ((fbeCurrentSize + LogonRawData.FBESize) > fbeStructSize)
                return true;
            if (!LogonRawData.Verify())
                return false;
            fbeCurrentSize += LogonRawData.FBESize;

            if ((fbeCurrentSize + MilliSecondTime.FBESize) > fbeStructSize)
                return true;
            if (!MilliSecondTime.Verify())
                return false;
            fbeCurrentSize += MilliSecondTime.FBESize;

            if ((fbeCurrentSize + QEnabled.FBESize) > fbeStructSize)
                return true;
            if (!QEnabled.Verify())
                return false;
            fbeCurrentSize += QEnabled.FBESize;

            if ((fbeCurrentSize + SessionStart.FBESize) > fbeStructSize)
                return true;
            if (!SessionStart.Verify())
                return false;
            fbeCurrentSize += SessionStart.FBESize;

            if ((fbeCurrentSize + SessionEnd.FBESize) > fbeStructSize)
                return true;
            if (!SessionEnd.Verify())
                return false;
            fbeCurrentSize += SessionEnd.FBESize;

            if ((fbeCurrentSize + TaskReset.FBESize) > fbeStructSize)
                return true;
            if (!TaskReset.Verify())
                return false;
            fbeCurrentSize += TaskReset.FBESize;

            if ((fbeCurrentSize + InSecNum.FBESize) > fbeStructSize)
                return true;
            if (!InSecNum.Verify())
                return false;
            fbeCurrentSize += InSecNum.FBESize;

            if ((fbeCurrentSize + OutSecNum.FBESize) > fbeStructSize)
                return true;
            if (!OutSecNum.Verify())
                return false;
            fbeCurrentSize += OutSecNum.FBESize;

            if ((fbeCurrentSize + LastUpdated.FBESize) > fbeStructSize)
                return true;
            if (!LastUpdated.Verify())
                return false;
            fbeCurrentSize += LastUpdated.FBESize;

            return true;
        }

        // Get the struct value (begin phase)
        public long GetBegin()
        {
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructOffset = ReadUInt32(FBEOffset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + 4 + 4) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + 4 + 4) > _buffer.Size))
                return 0;

            uint fbeStructSize = ReadUInt32(fbeStructOffset);
            Debug.Assert((fbeStructSize >= (4 + 4)), "Model is broken!");
            if (fbeStructSize < (4 + 4))
                return 0;

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Get the struct value (end phase)
        public void GetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Get the struct value
        public override void Get(out Config fbeValue) { Get(out fbeValue, Config.Default); }
        public override void Get(out Config fbeValue, Config defaults)
        {
            long fbeBegin = GetBegin();
            if (fbeBegin == 0)
            {
                fbeValue = defaults;
                return;
            }

            uint fbeStructSize = ReadUInt32(0);
            GetFields(out fbeValue, fbeStructSize);
            GetEnd(fbeBegin);
        }

        // Get the struct fields values
        public void GetFields(out Config fbeValue, long fbeStructSize)
        {
            long fbeCurrentSize = 4 + 4;

            fbeValue = Config.Default;

            if ((fbeCurrentSize + ConnectionID.FBESize) <= fbeStructSize)
                ConnectionID.Get(out fbeValue.ConnectionID);
            else
                fbeValue.ConnectionID = "";
            fbeCurrentSize += ConnectionID.FBESize;

            if ((fbeCurrentSize + Status.FBESize) <= fbeStructSize)
                Status.Get(out fbeValue.Status);
            else
                fbeValue.Status = global::proto.MessageStatus.Default;
            fbeCurrentSize += Status.FBESize;

            if ((fbeCurrentSize + SenderCompID.FBESize) <= fbeStructSize)
                SenderCompID.Get(out fbeValue.SenderCompID);
            else
                fbeValue.SenderCompID = "";
            fbeCurrentSize += SenderCompID.FBESize;

            if ((fbeCurrentSize + TargetCompID.FBESize) <= fbeStructSize)
                TargetCompID.Get(out fbeValue.TargetCompID);
            else
                fbeValue.TargetCompID = "";
            fbeCurrentSize += TargetCompID.FBESize;

            if ((fbeCurrentSize + IPAddress.FBESize) <= fbeStructSize)
                IPAddress.Get(out fbeValue.IPAddress);
            else
                fbeValue.IPAddress = "";
            fbeCurrentSize += IPAddress.FBESize;

            if ((fbeCurrentSize + BackUpIPAddress.FBESize) <= fbeStructSize)
                BackUpIPAddress.Get(out fbeValue.BackUpIPAddress);
            else
                fbeValue.BackUpIPAddress = "";
            fbeCurrentSize += BackUpIPAddress.FBESize;

            if ((fbeCurrentSize + Port.FBESize) <= fbeStructSize)
                Port.Get(out fbeValue.Port);
            else
                fbeValue.Port = (ulong)0UL;
            fbeCurrentSize += Port.FBESize;

            if ((fbeCurrentSize + BackUpPort.FBESize) <= fbeStructSize)
                BackUpPort.Get(out fbeValue.BackUpPort);
            else
                fbeValue.BackUpPort = (ulong)0UL;
            fbeCurrentSize += BackUpPort.FBESize;

            if ((fbeCurrentSize + Validate.FBESize) <= fbeStructSize)
                Validate.Get(out fbeValue.Validate);
            else
                fbeValue.Validate = "";
            fbeCurrentSize += Validate.FBESize;

            if ((fbeCurrentSize + HandleResend.FBESize) <= fbeStructSize)
                HandleResend.Get(out fbeValue.HandleResend);
            else
                fbeValue.HandleResend = "";
            fbeCurrentSize += HandleResend.FBESize;

            if ((fbeCurrentSize + HeartBeatInterval.FBESize) <= fbeStructSize)
                HeartBeatInterval.Get(out fbeValue.HeartBeatInterval);
            else
                fbeValue.HeartBeatInterval = (ulong)0UL;
            fbeCurrentSize += HeartBeatInterval.FBESize;

            if ((fbeCurrentSize + MaxLatency.FBESize) <= fbeStructSize)
                MaxLatency.Get(out fbeValue.MaxLatency);
            else
                fbeValue.MaxLatency = (ulong)0UL;
            fbeCurrentSize += MaxLatency.FBESize;

            if ((fbeCurrentSize + ResetConnection.FBESize) <= fbeStructSize)
                ResetConnection.Get(out fbeValue.ResetConnection);
            else
                fbeValue.ResetConnection = (ulong)0UL;
            fbeCurrentSize += ResetConnection.FBESize;

            if ((fbeCurrentSize + EnableConnection.FBESize) <= fbeStructSize)
                EnableConnection.Get(out fbeValue.EnableConnection);
            else
                fbeValue.EnableConnection = (ulong)0UL;
            fbeCurrentSize += EnableConnection.FBESize;

            if ((fbeCurrentSize + FIXVersion.FBESize) <= fbeStructSize)
                FIXVersion.Get(out fbeValue.FIXVersion);
            else
                fbeValue.FIXVersion = "";
            fbeCurrentSize += FIXVersion.FBESize;

            if ((fbeCurrentSize + InternalFIXVersion.FBESize) <= fbeStructSize)
                InternalFIXVersion.Get(out fbeValue.InternalFIXVersion);
            else
                fbeValue.InternalFIXVersion = "";
            fbeCurrentSize += InternalFIXVersion.FBESize;

            if ((fbeCurrentSize + Mode.FBESize) <= fbeStructSize)
                Mode.Get(out fbeValue.Mode);
            else
                fbeValue.Mode = "";
            fbeCurrentSize += Mode.FBESize;

            if ((fbeCurrentSize + DBEnabled.FBESize) <= fbeStructSize)
                DBEnabled.Get(out fbeValue.DBEnabled);
            else
                fbeValue.DBEnabled = (ulong)0UL;
            fbeCurrentSize += DBEnabled.FBESize;

            if ((fbeCurrentSize + LatencyEnabled.FBESize) <= fbeStructSize)
                LatencyEnabled.Get(out fbeValue.LatencyEnabled);
            else
                fbeValue.LatencyEnabled = (ulong)0UL;
            fbeCurrentSize += LatencyEnabled.FBESize;

            if ((fbeCurrentSize + AutoConnect.FBESize) <= fbeStructSize)
                AutoConnect.Get(out fbeValue.AutoConnect);
            else
                fbeValue.AutoConnect = (ulong)0UL;
            fbeCurrentSize += AutoConnect.FBESize;

            if ((fbeCurrentSize + AutoReconnect.FBESize) <= fbeStructSize)
                AutoReconnect.Get(out fbeValue.AutoReconnect);
            else
                fbeValue.AutoReconnect = (ulong)0UL;
            fbeCurrentSize += AutoReconnect.FBESize;

            if ((fbeCurrentSize + ReconnectDelay.FBESize) <= fbeStructSize)
                ReconnectDelay.Get(out fbeValue.ReconnectDelay);
            else
                fbeValue.ReconnectDelay = (ulong)0UL;
            fbeCurrentSize += ReconnectDelay.FBESize;

            if ((fbeCurrentSize + ConnectRetry.FBESize) <= fbeStructSize)
                ConnectRetry.Get(out fbeValue.ConnectRetry);
            else
                fbeValue.ConnectRetry = (ulong)0UL;
            fbeCurrentSize += ConnectRetry.FBESize;

            if ((fbeCurrentSize + LogonRawData.FBESize) <= fbeStructSize)
                LogonRawData.Get(out fbeValue.LogonRawData);
            else
                fbeValue.LogonRawData = "";
            fbeCurrentSize += LogonRawData.FBESize;

            if ((fbeCurrentSize + MilliSecondTime.FBESize) <= fbeStructSize)
                MilliSecondTime.Get(out fbeValue.MilliSecondTime);
            else
                fbeValue.MilliSecondTime = (ulong)0UL;
            fbeCurrentSize += MilliSecondTime.FBESize;

            if ((fbeCurrentSize + QEnabled.FBESize) <= fbeStructSize)
                QEnabled.Get(out fbeValue.QEnabled);
            else
                fbeValue.QEnabled = (ulong)0UL;
            fbeCurrentSize += QEnabled.FBESize;

            if ((fbeCurrentSize + SessionStart.FBESize) <= fbeStructSize)
                SessionStart.Get(out fbeValue.SessionStart);
            else
                fbeValue.SessionStart = "";
            fbeCurrentSize += SessionStart.FBESize;

            if ((fbeCurrentSize + SessionEnd.FBESize) <= fbeStructSize)
                SessionEnd.Get(out fbeValue.SessionEnd);
            else
                fbeValue.SessionEnd = "";
            fbeCurrentSize += SessionEnd.FBESize;

            if ((fbeCurrentSize + TaskReset.FBESize) <= fbeStructSize)
                TaskReset.Get(out fbeValue.TaskReset);
            else
                fbeValue.TaskReset = "";
            fbeCurrentSize += TaskReset.FBESize;

            if ((fbeCurrentSize + InSecNum.FBESize) <= fbeStructSize)
                InSecNum.Get(out fbeValue.InSecNum);
            else
                fbeValue.InSecNum = (ulong)0UL;
            fbeCurrentSize += InSecNum.FBESize;

            if ((fbeCurrentSize + OutSecNum.FBESize) <= fbeStructSize)
                OutSecNum.Get(out fbeValue.OutSecNum);
            else
                fbeValue.OutSecNum = (ulong)0UL;
            fbeCurrentSize += OutSecNum.FBESize;

            if ((fbeCurrentSize + LastUpdated.FBESize) <= fbeStructSize)
                LastUpdated.Get(out fbeValue.LastUpdated);
            else
                fbeValue.LastUpdated = "";
            fbeCurrentSize += LastUpdated.FBESize;
        }

        // Set the struct value (begin phase)
        public long SetBegin()
        {
            Debug.Assert(((_buffer.Offset + FBEOffset + FBESize) <= _buffer.Size), "Model is broken!");
            if ((_buffer.Offset + FBEOffset + FBESize) > _buffer.Size)
                return 0;

            uint fbeStructSize = (uint)FBEBody;
            uint fbeStructOffset = (uint)(_buffer.Allocate(fbeStructSize) - _buffer.Offset);
            Debug.Assert(((fbeStructOffset > 0) && ((_buffer.Offset + fbeStructOffset + fbeStructSize) <= _buffer.Size)), "Model is broken!");
            if ((fbeStructOffset == 0) || ((_buffer.Offset + fbeStructOffset + fbeStructSize) > _buffer.Size))
                return 0;

            Write(FBEOffset, fbeStructOffset);
            Write(fbeStructOffset, fbeStructSize);
            Write(fbeStructOffset + 4, (uint)FBEType);

            _buffer.Shift(fbeStructOffset);
            return fbeStructOffset;
        }

        // Set the struct value (end phase)
        public void SetEnd(long fbeBegin)
        {
            _buffer.Unshift(fbeBegin);
        }

        // Set the struct value
        public override void Set(Config fbeValue)
        {
            long fbeBegin = SetBegin();
            if (fbeBegin == 0)
                return;

            SetFields(fbeValue);
            SetEnd(fbeBegin);
        }

        // Set the struct fields values
        public void SetFields(Config fbeValue)
        {
            ConnectionID.Set(fbeValue.ConnectionID);
            Status.Set(fbeValue.Status);
            SenderCompID.Set(fbeValue.SenderCompID);
            TargetCompID.Set(fbeValue.TargetCompID);
            IPAddress.Set(fbeValue.IPAddress);
            BackUpIPAddress.Set(fbeValue.BackUpIPAddress);
            Port.Set(fbeValue.Port);
            BackUpPort.Set(fbeValue.BackUpPort);
            Validate.Set(fbeValue.Validate);
            HandleResend.Set(fbeValue.HandleResend);
            HeartBeatInterval.Set(fbeValue.HeartBeatInterval);
            MaxLatency.Set(fbeValue.MaxLatency);
            ResetConnection.Set(fbeValue.ResetConnection);
            EnableConnection.Set(fbeValue.EnableConnection);
            FIXVersion.Set(fbeValue.FIXVersion);
            InternalFIXVersion.Set(fbeValue.InternalFIXVersion);
            Mode.Set(fbeValue.Mode);
            DBEnabled.Set(fbeValue.DBEnabled);
            LatencyEnabled.Set(fbeValue.LatencyEnabled);
            AutoConnect.Set(fbeValue.AutoConnect);
            AutoReconnect.Set(fbeValue.AutoReconnect);
            ReconnectDelay.Set(fbeValue.ReconnectDelay);
            ConnectRetry.Set(fbeValue.ConnectRetry);
            LogonRawData.Set(fbeValue.LogonRawData);
            MilliSecondTime.Set(fbeValue.MilliSecondTime);
            QEnabled.Set(fbeValue.QEnabled);
            SessionStart.Set(fbeValue.SessionStart);
            SessionEnd.Set(fbeValue.SessionEnd);
            TaskReset.Set(fbeValue.TaskReset);
            InSecNum.Set(fbeValue.InSecNum);
            OutSecNum.Set(fbeValue.OutSecNum);
            LastUpdated.Set(fbeValue.LastUpdated);
        }
    }

} // namespace proto
} // namespace FBE

namespace FBE {
namespace proto {

    using global::proto;

    // Fast Binary Encoding Config model
    public class ConfigModel : Model
    {
        public readonly FieldModelConfig model;

        public ConfigModel() { model = new FieldModelConfig(Buffer, 4); }
        public ConfigModel(Buffer buffer) : base(buffer) { model = new FieldModelConfig(Buffer, 4); }

        // Get the model size
        public long FBESize => model.FBESize + model.FBEExtra;
        // Get the model type
        public const long FBETypeConst = FieldModelConfig.FBETypeConst;
        public long FBEType => FBETypeConst;

        // Check if the struct value is valid
        public bool Verify()
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
                return false;

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            if (fbeFullSize < model.FBESize)
                return false;

            return model.Verify();
        }

        // Create a new model (begin phase)
        public long CreateBegin()
        {
            long fbeBegin = Buffer.Allocate(4 + model.FBESize);
            return fbeBegin;
        }

        // Create a new model (end phase)
        public long CreateEnd(long fbeBegin)
        {
            long fbeEnd = Buffer.Size;
            uint fbeFullSize = (uint)(fbeEnd - fbeBegin);
            Write(model.FBEOffset - 4, fbeFullSize);
            return fbeFullSize;
        }

        // Serialize the struct value
        public long Serialize(Config value)
        {
            long fbeBegin = CreateBegin();
            model.Set(value);
            long fbeFullSize = CreateEnd(fbeBegin);
            return fbeFullSize;
        }

        // Deserialize the struct value
        public long Deserialize(out Config value)
        {
            if ((Buffer.Offset + model.FBEOffset - 4) > Buffer.Size)
            {
                value = Config.Default;
                return 0;
            }

            uint fbeFullSize = ReadUInt32(model.FBEOffset - 4);
            Debug.Assert((fbeFullSize >= model.FBESize), "Model is broken!");
            if (fbeFullSize < model.FBESize)
            {
                value = Config.Default;
                return 0;
            }

            model.Get(out value);
            return fbeFullSize;
        }

        // Move to the next struct value
        public void Next(long prev)
        {
            model.FBEShift(prev);
        }
    }

} // namespace proto
} // namespace FBE
